service: aws-node-http-api-project
frameworkVersion: '3.40.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

package:   
  individually: true


functions:
  helloWorld:
    handler: index.handler
   
        

  usuarioLogin:
    handler: functions/login/usuarioLogin.handler

  cargarDataS3:
    handler: utils/cargarDataS3.handler
    package:
      individually: true
      include:
        - utils/cargarDataS3.js
  
  lambdaAutorizer:
    handler: functions/auth/lambdaAutorizer.handler
    package:
      individually: true
      include:
        - functions/auth/lambdaAutorizer.js

#  USUARIOS
  agregarUsuario:
    handler: functions/usuario/agregarUsuario.handler
    package:
      individually: true
      include:
        - functions/usuario/agregarUsuario.js

  obtenerUsuarios:
    handler: functions/usuario/obtenerUsuarios.handler

#  RESERVAS
  agregarReserva:
    handler: functions/reserva/agregarReserva.handler
    package:
      individually: true
      include:
        - functions/reserva/agregarReserva.js

  obtenerReservas:
    handler: functions/reserva/obtenerReservas.handler
    package:
      individually: true
      include:
        - functions/reserva/obtenerReservas.js
  
  modificarReserva:
    handler: functions/reserva/modificarReserva.handler
    package:
      individually: true
      include:
        - functions/reserva/modificarReserva.js

  eliminarReserva:
    handler: functions/reserva/eliminarReserva.handler
    package:
      individually: true
      include:
        - functions/reserva/eliminarReserva.js

#  DOCENTE
  agregarDocente:
    handler: functions/docente/agregarDocente.handler
    package:
      individually: true
      include:
        - functions/docente/agregarDocente.js

  obtenerDocentes:
    handler: functions/docente/obtenerDocentes.handler
    package:
      individually: true
      include:
        - functions/docente/obtenerDocentes.js
  
  modificarDocente:
    handler: functions/docente/modificarDocente.handler
    package:
      individually: true
      include:
        - functions/docente/modificarDocente.js

  eliminarDocente:
    handler: functions/docente/eliminarDocente.handler
    package:
      individually: true
      include:
        - functions/docente/eliminarDocente.js
#  CONFIGURACIONES
  obtenerConfiguraciones:
      handler: functions/configuracion/obtenerConfiguraciones.handler
      package:
        individually: true
        include:
          - functions/configuracion/obtenerConfiguraciones.js