service: aws-node-http-api-project
frameworkVersion: '3.40.0'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    JWT_SECRET: ${.env:JWT_SECRET}
    USE_S3: ${.env:USE_S3}
  httpApi:
    cors:
      allowedOrigins:
        - '*'                          # O tus orígenes permitidos, ej: http://localhost:3000
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS

package:
  individually: true

functions:
  helloWorld:
    handler: index.handler
   
  obtenerUsuarios:
    handler: functions/usuario/obtenerUsuarios/index.handler   
        

  usuarioLogin:
    handler: functions/login/usuarioLogin/index.handler    

  agregarUsuario:
    handler: functions/usuario/agregarUsuario.handler
    package:
      include:
        - functions/usuario/agregarUsuario.js

  cargarDataS3:
    handler: utils/cargarDataS3.handler
    package:
      individually: true
      include:
        - utils/cargarDataS3.js
  
  lambdaAutorizer:
    handler: functions/auth/lambdaAutorizer.handler
    package:
      individually: true
      include:
        - functions/auth/lambdaAutorizer.js
