service: aws-node-http-api-project
frameworkVersion: "3.40.0"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

package:
  individually: true

functions:
  helloWorld:
    handler: index.handler

  usuarioLogin:
    handler: functions/login/usuarioLogin.handler

  cargarDataS3:
    handler: utils/cargarDataS3.handler
    package:
      individually: true
      include:
        - utils/cargarDataS3.js

  playground:
    handler: utils/playground.handler
    package:
      individually: true
      include:
        - utils/playground.js

  lambdaAutorizer:
    handler: functions/auth/lambdaAutorizer.handler
    package:
      individually: true
      include:
        - functions/auth/lambdaAutorizer.js

  #  USUARIOS
  agregarUsuario:
    handler: functions/usuario/agregarUsuario.handler
    package:
      individually: true
      include:
        - functions/usuario/agregarUsuario.js

  obtenerUsuarios:
    handler: functions/usuario/obtenerUsuarios.handler

  modificarUsuario:
    handler: functions/usuario/modificarUsuario.handler
    package:
      individually: true
      include:
        - functions/usuario/modificarUsuario.js

  #  RESERVAS
  agregarReserva:
    handler: functions/reserva/agregarReserva.handler
    package:
      individually: true
      include:
        - functions/reserva/agregarReserva.js

  obtenerReservas:
    handler: functions/reserva/obtenerReservas.handler
    package:
      individually: true
      include:
        - functions/reserva/obtenerReservas.js

  modificarReserva:
    handler: functions/reserva/modificarReserva.handler
    package:
      individually: true
      include:
        - functions/reserva/modificarReserva.js

  eliminarReserva:
    handler: functions/reserva/eliminarReserva.handler
    package:
      individually: true
      include:
        - functions/reserva/eliminarReserva.js

  #  DOCENTE
  agregarDocente:
    handler: functions/docente/agregarDocente.handler
    package:
      individually: true
      include:
        - functions/docente/agregarDocente.js

  obtenerDocentes:
    handler: functions/docente/obtenerDocentes.handler
    package:
      individually: true
      include:
        - functions/docente/obtenerDocentes.js

  modificarDocente:
    handler: functions/docente/modificarDocente.handler
    package:
      individually: true
      include:
        - functions/docente/modificarDocente.js

  eliminarDocente:
    handler: functions/docente/eliminarDocente.handler
    package:
      individually: true
      include:
        - functions/docente/eliminarDocente.js
  #  CONFIGURACIONES
  obtenerConfiguraciones:
    handler: functions/configuracion/obtenerConfiguraciones.handler
    package:
      individually: true
      include:
        - functions/configuracion/obtenerConfiguraciones.js

  agregarConfiguraciones:
    handler: functions/configuracion/agregarConfiguraciones.handler
    package:
      individually: true
      include:
        - functions/configuracion/agregarConfiguraciones.js

  modificarConfiguraciones:
    handler: functions/configuracion/modificarConfiguraciones.handler
    package:
      individually: true
      include:
        - functions/configuracion/modificarConfiguraciones.js

  eliminarConfiguraciones:
    handler: functions/configuracion/eliminarConfiguraciones.handler
    package:
      individually: true
      include:
        - functions/configuracion/eliminarConfiguraciones.js

  # DISPONIBLES
  obtenerDisponibles:
    handler: functions/disponible/obtenerDisponibles.handler
    package:
      individually: true
      include:
        - functions/disponible/obtenerDisponibles.js

  obtenerDisponiblesPor:
    handler: functions/disponible/obtenerDisponiblesPor.handler
    package:
      individually: true
      include:
        - functions/disponible/obtenerDisponiblesPor.js

  #  ALUMNOS
  obtenerAlumnos:
    handler: functions/alumno/obtenerAlumnos.handler
    package:
      individually: true
      include:
        - functions/alumno/obtenerAlumnos.js

  agregarAlumno:
    handler: functions/alumno/agregarAlumno.handler
    package:
      individually: true
      include:
        - functions/alumno/agregarAlumno.js

  modificarAlumno:
    handler: functions/alumno/modificarAlumno.handler
    package:
      individually: true
      include:
        - functions/alumno/modificarAlumno.js

  eliminarAlumno:
    handler: functions/alumno/eliminarAlumno.handler
    package:
      individually: true
      include:
        - functions/alumno/eliminarAlumno.js

  agregarReservaAlumno:
    handler: functions/alumnoReserva/agregarReservaAlumno.handler
    package:
      individually: true
      include:
        - functions/alumnoReserva/agregarReservaAlumno.js

  eliminarReservaAlumno:
    handler: functions/alumnoReserva/eliminarReservaAlumno.handler
    package:
      individually: true
      include:
        - functions/alumnoReserva/eliminarReservaAlumno.js
